### ISSUE TITLE
Facing issue in showing google 3d map tiles in unity editor and vision pro emulator

### ISSUE THREAD

**Issue by shahmeer1124** [HoloLabInc/ProjectSpirare-for-Unity#222]
Although I followed all the steps in your documentation, the Google map 3D tiles on the Unity editor and the vision pro are showing blank screen.
these are instructions you provided for the vision pro which i followed exactly
https://github.com/HoloLabInc/ProjectSpirare-for-Unity/tree/main/unity/SpirareBrowser-visionOS-3DMaps#edit-cesium-for-unity

<img width="1445" alt="Screenshot 2024-09-03 at 2 08 09 PM" src="https://github.com/user-attachments/assets/b422e352-b299-4982-88bf-20bd9188aa2b">
<img width="1512" alt="Screenshot 2024-09-03 at 4 02 05 PM" src="https://github.com/user-attachments/assets/dc279545-cfa1-4726-9556-a86ad7446bcc">

**Comment by tarukosu** [comment]
Did you set the tile URL in the GooglePhotorealistic3DTilesSourceSettings?
https://github.com/HoloLabInc/ProjectSpirare-for-Unity/tree/main/unity/SpirareBrowser-visionOS-3DMaps#set-api-key

**Comment by shahmeer1124** [comment]
yes i did

**Comment by tarukosu** [comment]
Could you please check the **Show Tiles In Hierarchy** option during runtime in the Unity Editor and verify that the tiles are loaded as child elements under **GooglePhotorealistic3DTiles**?

![image](https://github.com/user-attachments/assets/cafc3381-91b0-461d-9911-e4eeb718ab7a)

Could you also let me know the value of the Origin in the CesiumGeoreference?
![image](https://github.com/user-attachments/assets/497058b5-510c-4eb8-99d6-d82c313a8646)

**Comment by shahmeer1124** [comment]
in the runtime this is how my Hierarchy looks like 
<img width="1512" alt="Screenshot 2024-09-04 at 1 11 49 PM" src="https://github.com/user-attachments/assets/2d742d3a-b7bb-429d-bedc-92653669ff90">

and these are the values of origin

<img width="1512" alt="Screenshot 2024-09-04 at 1 11 49 PM" src="https://github.com/user-attachments/assets/644b4c4d-6631-40ca-b97c-9f515b5daada">

**Comment by tarukosu** [comment]
The first image is not in Play mode, right?
Could you check **Show Tiles In Hierarchy** and enter Play mode in the Editor?

The URL should be set in the **GooglePhotorealistic3DTilesSourceSettings** within the Assets, not in the **GooglePhotorealistic3DTiles** on the scene.

**Comment by shahmeer1124** [comment]
First of all Thankyou so much it is working now <3
just want to know any guess about on zooming out it should turn into a globe.

**Comment by tarukosu** [comment]
Ideally, it would turn into a sphere when zoomed out.
But the adjustment of the terrain height becomes more complex, so it has not been implemented yet.
