### ISSUE TITLE
Update Cesium to 1.13.0?

### ISSUE THREAD

**Issue by kkkarannn** [HoloLabInc/ProjectSpirare-for-Unity#231]
Are there any plans to update cesium to the latest version?

**Comment by tarukosu** [comment]
A clear plan wasn't in place, but it will be updated before the next release.

**Comment by tarukosu** [comment]
@kkkarannn 
I have updated Cesium for Unity to version v1.14.0.
https://github.com/HoloLabInc/ProjectSpirare-for-Unity/pull/240
