### ISSUE TITLE
Google Map 3d Tiles are not visible in vision pro emulator

### ISSUE THREAD

**Issue by saqlainjamil5** [HoloLabInc/ProjectSpirare-for-Unity#235]
![Image](https://github.com/user-attachments/assets/75d394b2-d649-4e98-a141-c90a1eb02f69)
I updated my Xcode and Vision Emulator to version 2.0 After the update, the map looks like this Can you tell me how to solve this issue?

**Comment by tarukosu** [comment]
The issue did not occur in my environment.
- XCode 16.0
- Vision OS Emulator version 2.0

The cause of the issue might be the recent update, which included upgrading Cesium for Unity and updating the shaders.
Could you try setting it up again using the latest version?
https://github.com/HoloLabInc/ProjectSpirare-for-Unity/tree/main/unity/SpirareBrowser-visionOS-3DMaps#project-setup
